"""initial revision

Revision ID: 1e8e322dfbc6
Revises: 
Create Date: 2016-02-29 16:38:09.879357

"""

# revision identifiers, used by Alembic.
revision = '1e8e322dfbc6'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=32), nullable=False),
    sa.Column('special', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_groups_group_name'), 'groups', ['group_name'], unique=True)
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('invitation_iid', sa.Integer(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('avatar_url', sa.String(length=120), nullable=True),
    sa.Column('dietary_requirements', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['invitation_iid'], ['invitations.iid'], use_alter=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('social_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('group_link',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['groups.gid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'gid')
    )
    op.create_table('invitations',
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.Column('total_guests', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('iid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    op.drop_table('group_link')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_groups_group_name'), table_name='groups')
    op.drop_table('groups')
    ### end Alembic commands ###
