"""add todo support

Revision ID: 1ed0ce6e2d95
Revises: 1e8e322dfbc6
Create Date: 2016-02-29 16:40:27.489421

"""

# revision identifiers, used by Alembic.
revision = '1ed0ce6e2d95'
down_revision = '1e8e322dfbc6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_foreign_key(None, 'users', 'invitations', ['invitation_iid'], ['iid'], use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_table('todos')
    ### end Alembic commands ###
